// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        imgR_in_data_dout,
        imgR_in_data_num_data_valid,
        imgR_in_data_fifo_cap,
        imgR_in_data_empty_n,
        imgR_in_data_read,
        rightRemappedMat_data_din,
        rightRemappedMat_data_num_data_valid,
        rightRemappedMat_data_fifo_cap,
        rightRemappedMat_data_full_n,
        rightRemappedMat_data_write,
        mapxRMat_data_dout,
        mapxRMat_data_num_data_valid,
        mapxRMat_data_fifo_cap,
        mapxRMat_data_empty_n,
        mapxRMat_data_read,
        mapyRMat_data_dout,
        mapyRMat_data_num_data_valid,
        mapyRMat_data_fifo_cap,
        mapyRMat_data_empty_n,
        mapyRMat_data_read,
        p_read,
        p_read1
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] imgR_in_data_dout;
input  [1:0] imgR_in_data_num_data_valid;
input  [1:0] imgR_in_data_fifo_cap;
input   imgR_in_data_empty_n;
output   imgR_in_data_read;
output  [7:0] rightRemappedMat_data_din;
input  [1:0] rightRemappedMat_data_num_data_valid;
input  [1:0] rightRemappedMat_data_fifo_cap;
input   rightRemappedMat_data_full_n;
output   rightRemappedMat_data_write;
input  [31:0] mapxRMat_data_dout;
input  [1:0] mapxRMat_data_num_data_valid;
input  [1:0] mapxRMat_data_fifo_cap;
input   mapxRMat_data_empty_n;
output   mapxRMat_data_read;
input  [31:0] mapyRMat_data_dout;
input  [1:0] mapyRMat_data_num_data_valid;
input  [1:0] mapyRMat_data_fifo_cap;
input   mapyRMat_data_empty_n;
output   mapyRMat_data_read;
input  [15:0] p_read;
input  [15:0] p_read1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg imgR_in_data_read;
reg rightRemappedMat_data_write;
reg mapxRMat_data_read;
reg mapyRMat_data_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire   [16:0] rows_cast_i_fu_138_p1;
reg   [16:0] rows_cast_i_reg_285;
wire   [16:0] cols_cast_i_fu_142_p1;
reg   [16:0] cols_cast_i_reg_291;
wire   [16:0] sub284_i_fu_146_p2;
reg   [16:0] sub284_i_reg_296;
wire   [16:0] sub300_i_fu_152_p2;
reg   [16:0] sub300_i_reg_301;
wire    ap_CS_fsm_state2;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_done;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_done;
reg    ap_block_state2_on_subcall_done;
wire   [16:0] add_i_fu_171_p2;
reg   [16:0] add_i_reg_316;
wire    ap_CS_fsm_state7;
wire   [16:0] add106_i_fu_176_p2;
reg   [16:0] add106_i_reg_321;
wire   [31:0] grp_fu_132_p1;
reg   [31:0] conv3_i_reg_326;
wire   [31:0] grp_fu_135_p1;
reg   [31:0] conv4_i_reg_331;
wire   [30:0] trunc_ln347_fu_185_p1;
reg   [30:0] trunc_ln347_reg_336;
wire   [22:0] trunc_ln347_2_fu_189_p1;
reg   [22:0] trunc_ln347_2_reg_341;
wire   [30:0] trunc_ln348_fu_197_p1;
reg   [30:0] trunc_ln348_reg_346;
wire   [22:0] trunc_ln348_2_fu_201_p1;
reg   [22:0] trunc_ln348_2_reg_351;
reg   [16:0] i_5_reg_356;
wire    ap_CS_fsm_state8;
wire   [0:0] trunc_ln249_fu_208_p1;
reg   [0:0] trunc_ln249_reg_362;
wire   [6:0] trunc_ln249_2_fu_212_p1;
reg   [6:0] trunc_ln249_2_reg_367;
wire   [0:0] cmp111_i_fu_227_p2;
reg   [0:0] cmp111_i_reg_375;
wire   [0:0] icmp_ln249_fu_216_p2;
wire   [14:0] mul_ln314_fu_246_p2;
reg   [14:0] mul_ln314_reg_380;
wire   [0:0] icmp_fu_266_p2;
reg   [0:0] icmp_reg_385;
wire    ap_CS_fsm_state9;
reg   [6:0] r1_address0;
reg    r1_ce0;
reg    r1_we0;
reg   [16:0] r1_d0;
reg    r1_ce1;
wire   [16:0] r1_q1;
reg   [6:0] r2_address0;
reg    r2_ce0;
reg    r2_we0;
reg   [16:0] r2_d0;
reg    r2_ce1;
wire   [16:0] r2_q1;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_start;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_idle;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_ready;
wire   [6:0] grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_r1_address0;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_r1_ce0;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_r1_we0;
wire   [16:0] grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_r1_d0;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_start;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_idle;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_ready;
wire   [6:0] grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_r2_address0;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_r2_ce0;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_r2_we0;
wire   [16:0] grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_r2_d0;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_start;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_done;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_idle;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_ready;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_imgR_in_data_read;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_mapxRMat_data_read;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_mapyRMat_data_read;
wire   [7:0] grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_rightRemappedMat_data_din;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_rightRemappedMat_data_write;
wire   [6:0] grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_address0;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_ce0;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_we0;
wire   [16:0] grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_d0;
wire   [6:0] grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_address1;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_ce1;
wire   [6:0] grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_address0;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_ce0;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_we0;
wire   [16:0] grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_d0;
wire   [6:0] grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_address1;
wire    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_ce1;
reg    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_start_reg;
reg    ap_block_state1_ignore_call9;
reg    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_start_reg;
reg    ap_block_state1_ignore_call10;
reg    grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_start_reg;
wire    ap_CS_fsm_state10;
reg   [16:0] i_fu_68;
wire   [16:0] i_6_fu_221_p2;
wire  signed [31:0] grp_fu_132_p0;
wire  signed [31:0] grp_fu_135_p0;
wire   [31:0] bitcast_ln347_fu_181_p1;
wire   [31:0] bitcast_ln348_fu_193_p1;
wire   [5:0] div228_i_fu_232_p4;
wire   [5:0] mul_ln314_fu_246_p0;
wire   [9:0] mul_ln314_fu_246_p1;
wire   [10:0] tmp_fu_257_p4;
reg    grp_fu_132_ce;
reg    grp_fu_135_ce;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire   [14:0] mul_ln314_fu_246_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_start_reg = 1'b0;
#0 grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_start_reg = 1'b0;
#0 grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_start_reg = 1'b0;
end

stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_s_r1_RAM_AUTO_1R1W #(
    .DataWidth( 17 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
r1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(r1_address0),
    .ce0(r1_ce0),
    .we0(r1_we0),
    .d0(r1_d0),
    .address1(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_address1),
    .ce1(r1_ce1),
    .q1(r1_q1)
);

stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_s_r1_RAM_AUTO_1R1W #(
    .DataWidth( 17 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
r2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(r2_address0),
    .ce0(r2_ce0),
    .we0(r2_we0),
    .d0(r2_d0),
    .address1(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_address1),
    .ce1(r2_ce1),
    .q1(r2_q1)
);

stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1 grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_start),
    .ap_done(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_done),
    .ap_idle(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_idle),
    .ap_ready(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_ready),
    .r1_address0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_r1_address0),
    .r1_ce0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_r1_ce0),
    .r1_we0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_r1_we0),
    .r1_d0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_r1_d0)
);

stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2 grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_start),
    .ap_done(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_done),
    .ap_idle(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_idle),
    .ap_ready(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_ready),
    .r2_address0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_r2_address0),
    .r2_ce0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_r2_ce0),
    .r2_we0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_r2_we0),
    .r2_d0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_r2_d0)
);

stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_start),
    .ap_done(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_done),
    .ap_idle(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_idle),
    .ap_ready(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_ready),
    .imgR_in_data_dout(imgR_in_data_dout),
    .imgR_in_data_num_data_valid(2'd0),
    .imgR_in_data_fifo_cap(2'd0),
    .imgR_in_data_empty_n(imgR_in_data_empty_n),
    .imgR_in_data_read(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_imgR_in_data_read),
    .mapxRMat_data_dout(mapxRMat_data_dout),
    .mapxRMat_data_num_data_valid(2'd0),
    .mapxRMat_data_fifo_cap(2'd0),
    .mapxRMat_data_empty_n(mapxRMat_data_empty_n),
    .mapxRMat_data_read(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_mapxRMat_data_read),
    .mapyRMat_data_dout(mapyRMat_data_dout),
    .mapyRMat_data_num_data_valid(2'd0),
    .mapyRMat_data_fifo_cap(2'd0),
    .mapyRMat_data_empty_n(mapyRMat_data_empty_n),
    .mapyRMat_data_read(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_mapyRMat_data_read),
    .rightRemappedMat_data_din(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_rightRemappedMat_data_din),
    .rightRemappedMat_data_num_data_valid(2'd0),
    .rightRemappedMat_data_fifo_cap(2'd0),
    .rightRemappedMat_data_full_n(rightRemappedMat_data_full_n),
    .rightRemappedMat_data_write(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_rightRemappedMat_data_write),
    .r2_address0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_address0),
    .r2_ce0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_ce0),
    .r2_we0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_we0),
    .r2_d0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_d0),
    .r2_address1(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_address1),
    .r2_ce1(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_ce1),
    .r2_q1(r2_q1),
    .idxprom2582_i(trunc_ln249_2_reg_367),
    .r1_address0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_address0),
    .r1_ce0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_ce0),
    .r1_we0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_we0),
    .r1_d0(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_d0),
    .r1_address1(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_address1),
    .r1_ce1(grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_ce1),
    .r1_q1(r1_q1),
    .add106_i(add106_i_reg_321),
    .i(i_5_reg_356),
    .cmp263_i(icmp_reg_385),
    .mul_ln314(mul_ln314_reg_380),
    .trunc_ln(trunc_ln249_reg_362),
    .cols_cast_i(p_read1),
    .cmp111_i(cmp111_i_reg_375),
    .bitcast_ln347(trunc_ln347_reg_336),
    .trunc_ln347_2(trunc_ln347_2_reg_341),
    .conv3_i(conv3_i_reg_326),
    .bitcast_ln348(trunc_ln348_reg_346),
    .trunc_ln348_2(trunc_ln348_2_reg_351),
    .conv4_i(conv4_i_reg_331)
);

stereolbm_axis_cambm_sitofp_32s_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_6_no_dsp_1_U329(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_132_p0),
    .ce(grp_fu_132_ce),
    .dout(grp_fu_132_p1)
);

stereolbm_axis_cambm_sitofp_32s_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_6_no_dsp_1_U330(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_135_p0),
    .ce(grp_fu_135_ce),
    .dout(grp_fu_135_p1)
);

stereolbm_axis_cambm_mul_6ns_10ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 15 ))
mul_6ns_10ns_15_1_1_U331(
    .din0(mul_ln314_fu_246_p0),
    .din1(mul_ln314_fu_246_p1),
    .dout(mul_ln314_fu_246_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln249_fu_216_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_start_reg <= 1'b1;
        end else if ((grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_ready == 1'b1)) begin
            grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_ready == 1'b1)) begin
            grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_start_reg <= 1'b1;
        end else if ((grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_ready == 1'b1)) begin
            grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_68 <= 17'd0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln249_fu_216_p2 == 1'd0))) begin
        i_fu_68 <= i_6_fu_221_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add106_i_reg_321 <= add106_i_fu_176_p2;
        add_i_reg_316 <= add_i_fu_171_p2;
        conv3_i_reg_326 <= grp_fu_132_p1;
        conv4_i_reg_331 <= grp_fu_135_p1;
        trunc_ln347_2_reg_341 <= trunc_ln347_2_fu_189_p1;
        trunc_ln347_reg_336 <= trunc_ln347_fu_185_p1;
        trunc_ln348_2_reg_351 <= trunc_ln348_2_fu_201_p1;
        trunc_ln348_reg_346 <= trunc_ln348_fu_197_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln249_fu_216_p2 == 1'd0))) begin
        cmp111_i_reg_375 <= cmp111_i_fu_227_p2;
        mul_ln314_reg_380 <= mul_ln314_fu_246_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_cast_i_reg_291[15 : 0] <= cols_cast_i_fu_142_p1[15 : 0];
        rows_cast_i_reg_285[15 : 0] <= rows_cast_i_fu_138_p1[15 : 0];
        sub284_i_reg_296 <= sub284_i_fu_146_p2;
        sub300_i_reg_301 <= sub300_i_fu_152_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        i_5_reg_356 <= i_fu_68;
        trunc_ln249_2_reg_367 <= trunc_ln249_2_fu_212_p1;
        trunc_ln249_reg_362 <= trunc_ln249_fu_208_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        icmp_reg_385 <= icmp_fu_266_p2;
    end
end

always @ (*) begin
    if ((grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln249_fu_216_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln249_fu_216_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | ((1'b1 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2)))) begin
        grp_fu_132_ce = 1'b0;
    end else begin
        grp_fu_132_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | ((1'b1 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2)))) begin
        grp_fu_135_ce = 1'b0;
    end else begin
        grp_fu_135_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        imgR_in_data_read = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_imgR_in_data_read;
    end else begin
        imgR_in_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        mapxRMat_data_read = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_mapxRMat_data_read;
    end else begin
        mapxRMat_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        mapyRMat_data_read = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_mapyRMat_data_read;
    end else begin
        mapyRMat_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        r1_address0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        r1_address0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_r1_address0;
    end else begin
        r1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        r1_ce0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        r1_ce0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_r1_ce0;
    end else begin
        r1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        r1_ce1 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_ce1;
    end else begin
        r1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        r1_d0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        r1_d0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_r1_d0;
    end else begin
        r1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        r1_we0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        r1_we0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_r1_we0;
    end else begin
        r1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        r2_address0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        r2_address0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_r2_address0;
    end else begin
        r2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        r2_ce0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        r2_ce0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_r2_ce0;
    end else begin
        r2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        r2_ce1 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_ce1;
    end else begin
        r2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        r2_d0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        r2_d0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_r2_d0;
    end else begin
        r2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        r2_we0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_r2_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        r2_we0 = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_r2_we0;
    end else begin
        r2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        rightRemappedMat_data_write = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_rightRemappedMat_data_write;
    end else begin
        rightRemappedMat_data_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln249_fu_216_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add106_i_fu_176_p2 = (cols_cast_i_reg_291 + 17'd1);

assign add_i_fu_171_p2 = (rows_cast_i_reg_285 + 17'd64);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call10 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call9 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_done == 1'b0) | (grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_done == 1'b0));
end

assign bitcast_ln347_fu_181_p1 = grp_fu_132_p1;

assign bitcast_ln348_fu_193_p1 = grp_fu_135_p1;

assign cmp111_i_fu_227_p2 = ((i_fu_68 < rows_cast_i_reg_285) ? 1'b1 : 1'b0);

assign cols_cast_i_fu_142_p1 = p_read1;

assign div228_i_fu_232_p4 = {{i_fu_68[6:1]}};

assign grp_fu_132_p0 = $signed(sub284_i_reg_296);

assign grp_fu_135_p0 = $signed(sub300_i_reg_301);

assign grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_start = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1_fu_92_ap_start_reg;

assign grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_start = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2_fu_98_ap_start_reg;

assign grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_start = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_ap_start_reg;

assign i_6_fu_221_p2 = (i_fu_68 + 17'd1);

assign icmp_fu_266_p2 = ((tmp_fu_257_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_216_p2 = ((i_fu_68 == add_i_reg_316) ? 1'b1 : 1'b0);

assign mul_ln314_fu_246_p0 = mul_ln314_fu_246_p00;

assign mul_ln314_fu_246_p00 = div228_i_fu_232_p4;

assign mul_ln314_fu_246_p1 = 15'd401;

assign rightRemappedMat_data_din = grp_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width_fu_104_rightRemappedMat_data_din;

assign rows_cast_i_fu_138_p1 = p_read;

assign sub284_i_fu_146_p2 = ($signed(rows_cast_i_fu_138_p1) + $signed(17'd131071));

assign sub300_i_fu_152_p2 = ($signed(cols_cast_i_fu_142_p1) + $signed(17'd131071));

assign tmp_fu_257_p4 = {{i_5_reg_356[16:6]}};

assign trunc_ln249_2_fu_212_p1 = i_fu_68[6:0];

assign trunc_ln249_fu_208_p1 = i_fu_68[0:0];

assign trunc_ln347_2_fu_189_p1 = bitcast_ln347_fu_181_p1[22:0];

assign trunc_ln347_fu_185_p1 = bitcast_ln347_fu_181_p1[30:0];

assign trunc_ln348_2_fu_201_p1 = bitcast_ln348_fu_193_p1[22:0];

assign trunc_ln348_fu_197_p1 = bitcast_ln348_fu_193_p1[30:0];

always @ (posedge ap_clk) begin
    rows_cast_i_reg_285[16] <= 1'b0;
    cols_cast_i_reg_291[16] <= 1'b0;
end

endmodule //stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_s
