#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Script generated by Vivado on Tue Jun 24 20:41:12 +0100 2025
# SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
#
# Tool Version Limit: 2023.05 
#
# Filename     : design_1.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : design_1.sh
#                design_1.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                design_1.sh [-reset_run]
#                design_1.sh [-reset_log]
#                design_1.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the Xilinx simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'design_1.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname axi_lite_ipif_v3_0_4 -libname v_tc_v6_2_6 -libname xil_defaultlib -libname v_tc_v6_1_13 -libname v_vid_in_axi4s_v4_0_9 -libname v_axi4s_vid_out_v4_0_16 -libname xlconstant_v1_1_7 -libname lib_cdc_v1_0_2 -libname proc_sys_reset_v5_0_13 -libname xbip_utils_v3_0_10 -libname axi_utils_v2_0_6 -libname xbip_pipe_v3_0_6 -libname xbip_dsp48_wrapper_v3_0_4 -libname xbip_dsp48_addsub_v3_0_6 -libname xbip_bram18k_v3_0_6 -libname mult_gen_v12_0_18 -libname floating_point_v7_0_20 -libname xbip_dsp48_mult_v3_0_6 -libname xbip_dsp48_multadd_v3_0_6 -libname div_gen_v5_1_19 -libname v_frmbuf_wr_v2_4_0 -libname v_frmbuf_rd_v2_4_0 -libname v_vid_in_axi4s_v5_0_2 -libname axi_infrastructure_v1_1_0 -libname axi_vip_v1_1_14 -libname processing_system7_vip_v1_0_16 -libname xlconcat_v2_1_4 -libname axis_infrastructure_v1_1_0 -libname axis_register_slice_v1_1_28 -libname axis_subset_converter_v1_1_28 -libname generic_baseblocks_v2_1_0 -libname axi_register_slice_v2_1_28 -libname fifo_generator_v13_2_8 -libname axi_data_fifo_v2_1_27 -libname axi_crossbar_v2_1_29 -libname floating_point_v7_1_15 -libname axi_protocol_converter_v2_1_28 -libname axi_clock_converter_v2_1_27 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm axi_lite_ipif_v3_0_4 v_tc_v6_2_6 xil_defaultlib v_tc_v6_1_13 v_vid_in_axi4s_v4_0_9 v_axi4s_vid_out_v4_0_16 xlconstant_v1_1_7 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 xbip_utils_v3_0_10 axi_utils_v2_0_6 xbip_pipe_v3_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_18 floating_point_v7_0_20 xbip_dsp48_mult_v3_0_6 xbip_dsp48_multadd_v3_0_6 div_gen_v5_1_19 v_frmbuf_wr_v2_4_0 v_frmbuf_rd_v2_4_0 v_vid_in_axi4s_v5_0_2 axi_infrastructure_v1_1_0 axi_vip_v1_1_14 processing_system7_vip_v1_0_16 xlconcat_v2_1_4 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_28 axis_subset_converter_v1_1_28 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_28 fifo_generator_v13_2_8 axi_data_fifo_v2_1_27 axi_crossbar_v2_1_29 floating_point_v7_1_15 axi_protocol_converter_v2_1_28 axi_clock_converter_v2_1_27)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2023.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "C:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "C:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm $xmvhdl_opts \
  "C:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work v_tc_v6_2_6 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/0350/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_v_tc_0_0/sim/design_1_v_tc_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work v_tc_v6_1_13 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work v_vid_in_axi4s_v4_0_9 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work v_axi4s_vid_out_v4_0_16 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/c523/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/sim/design_1_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_7 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/b0f2/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xlconstant_0_0/sim/design_1_xlconstant_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_2 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_13 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_rst_ps7_0_100M_0/sim/design_1_rst_ps7_0_100M_0.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/20df/src/ClockGen.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/20df/src/SyncAsync.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/20df/src/SyncAsyncReset.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/20df/src/DVI_Constants.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/20df/src/OutputSERDES.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/20df/src/TMDS_Encoder.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/20df/src/rgb2dvi.vhd" \
  "../../../bd/design_1/ip/design_1_rgb2dvi_0_1/sim/design_1_rgb2dvi_0_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/9097/src/mmcme2_drp.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/9097/src/axi_dynclk_S00_AXI.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/9097/src/axi_dynclk.vhd" \
  "../../../bd/design_1/ip/design_1_axi_dynclk_0_0/sim/design_1_axi_dynclk_0_0.vhd" \
  "../../../bd/design_1/ip/design_1_proc_sys_reset_0_1/sim/design_1_proc_sys_reset_0_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xlconstant_1_0/sim/design_1_xlconstant_1_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xbip_utils_v3_0_10 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_utils_v2_0_6 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_pipe_v3_0_6 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_wrapper_v3_0_4 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_addsub_v3_0_6 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_bram18k_v3_0_6 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work mult_gen_v12_0_18 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work floating_point_v7_0_20 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_mult_v3_0_6 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_multadd_v3_0_6 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work div_gen_v5_1_19 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/hdl/div_gen_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work v_frmbuf_wr_v2_4_0 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/hdl/v_frmbuf_wr_v2_4_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_v_frmbuf_wr_0_0/sim/design_1_v_frmbuf_wr_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work v_frmbuf_rd_v2_4_0 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_rd_0_0/hdl/v_frmbuf_rd_v2_4_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_v_frmbuf_rd_0_0/sim/design_1_v_frmbuf_rd_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work v_vid_in_axi4s_v5_0_2 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/9649/hdl/v_vid_in_axi4s_v5_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_v_vid_in_axi4s_0_0/sim/design_1_v_vid_in_axi4s_0_0.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_14 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ed63/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work processing_system7_vip_v1_0_16 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_processing_system7_0_1/sim/design_1_processing_system7_0_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ipshared/420f/src/ov5640_capture_yuv.vhd" \
  "../../../bd/design_1/ip/design_1_ov5640_capture_yuv_0_0/sim/design_1_ov5640_capture_yuv_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xlconcat_v2_1_4 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xlconcat_0_0/sim/design_1_xlconcat_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_ov5640_capture_yuv_1_0/sim/design_1_ov5640_capture_yuv_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_v_vid_in_axi4s_0_1/sim/design_1_v_vid_in_axi4s_0_1.v" \
  "../../../bd/design_1/ip/design_1_v_frmbuf_wr_0_1/sim/design_1_v_frmbuf_wr_0_1.v" \
  "../../../bd/design_1/ip/design_1_v_frmbuf_rd_0_1/sim/design_1_v_frmbuf_rd_0_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_infrastructure_v1_1_0 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_register_slice_v1_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/eb9f/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tdata_design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tuser_design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tstrb_design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tkeep_design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tid_design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tdest_design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tlast_design_1_axis_subset_converter_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_subset_converter_v1_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/d78a/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/top_design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/sim/design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_2_0/hdl/tdata_design_1_axis_subset_converter_2_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_2_0/hdl/tuser_design_1_axis_subset_converter_2_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_2_0/hdl/tstrb_design_1_axis_subset_converter_2_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_2_0/hdl/tkeep_design_1_axis_subset_converter_2_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_2_0/hdl/tid_design_1_axis_subset_converter_2_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_2_0/hdl/tdest_design_1_axis_subset_converter_2_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_2_0/hdl/tlast_design_1_axis_subset_converter_2_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_2_0/hdl/top_design_1_axis_subset_converter_2_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_2_0/sim/design_1_axis_subset_converter_2_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/tdata_design_1_axis_subset_converter_0_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/tuser_design_1_axis_subset_converter_0_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/tstrb_design_1_axis_subset_converter_0_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/tkeep_design_1_axis_subset_converter_0_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/tid_design_1_axis_subset_converter_0_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/tdest_design_1_axis_subset_converter_0_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/tlast_design_1_axis_subset_converter_0_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/top_design_1_axis_subset_converter_0_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/sim/design_1_axis_subset_converter_0_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_0/hdl/tdata_design_1_axis_subset_converter_3_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_0/hdl/tuser_design_1_axis_subset_converter_3_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_0/hdl/tstrb_design_1_axis_subset_converter_3_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_0/hdl/tkeep_design_1_axis_subset_converter_3_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_0/hdl/tid_design_1_axis_subset_converter_3_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_0/hdl/tdest_design_1_axis_subset_converter_3_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_0/hdl/tlast_design_1_axis_subset_converter_3_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_0/hdl/top_design_1_axis_subset_converter_3_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_0/sim/design_1_axis_subset_converter_3_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_0 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/87d1/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_8 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/c97d/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_8 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_8 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_27 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/fab7/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_29 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/f8f3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xbar_4/sim/design_1_xbar_4.v" \
  "../../../bd/design_1/ip/design_1_xbar_5/sim/design_1_xbar_5.v" \
  "../../../bd/design_1/ip/design_1_v_frmbuf_wr_2_0/sim/design_1_v_frmbuf_wr_2_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_1/hdl/tdata_design_1_axis_subset_converter_3_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_1/hdl/tuser_design_1_axis_subset_converter_3_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_1/hdl/tstrb_design_1_axis_subset_converter_3_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_1/hdl/tkeep_design_1_axis_subset_converter_3_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_1/hdl/tid_design_1_axis_subset_converter_3_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_1/hdl/tdest_design_1_axis_subset_converter_3_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_1/hdl/tlast_design_1_axis_subset_converter_3_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_1/hdl/top_design_1_axis_subset_converter_3_1.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_1/sim/design_1_axis_subset_converter_3_1.v" \
  "../../../bd/design_1/ip/design_1_v_frmbuf_rd_2_0/sim/design_1_v_frmbuf_rd_2_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_2/hdl/tdata_design_1_axis_subset_converter_3_2.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_2/hdl/tuser_design_1_axis_subset_converter_3_2.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_2/hdl/tstrb_design_1_axis_subset_converter_3_2.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_2/hdl/tkeep_design_1_axis_subset_converter_3_2.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_2/hdl/tid_design_1_axis_subset_converter_3_2.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_2/hdl/tdest_design_1_axis_subset_converter_3_2.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_2/hdl/tlast_design_1_axis_subset_converter_3_2.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_2/hdl/top_design_1_axis_subset_converter_3_2.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_3_2/sim/design_1_axis_subset_converter_3_2.v" \
  "../../../bd/design_1/ip/design_1_xbar_6/sim/design_1_xbar_6.v" \
  "../../../bd/design_1/ip/design_1_xbar_7/sim/design_1_xbar_7.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work floating_point_v7_1_15 $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/22f8/hdl/floating_point_v7_1_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work floating_point_v7_1_15 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/22f8/hdl/floating_point_v7_1_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_ama_submuladd_11ns_11ns_8ns_18ns_18_4_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_Pipeline_loop_col_zxi2mat.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_Pipeline_loop_last_hunt.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_Pipeline_loop_start_hunt.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_s.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_Block_for_end72_proc.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_Block_for_end7235_proc.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_cameraMA_l_fix_RAM_AUTO_1R1W.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_cameraMA_l_fix_RAM_AUTO_1R1W_memcore.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_ConvertShiftAbs.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_ConvertShiftAbs_Pipeline_loop_width.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_Ctrl_s_axi.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_distC_l_fix_RAM_AUTO_1R1W.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_distC_l_fix_RAM_AUTO_1R1W_memcore.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_entry_proc.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fcmp_32ns_32ns_1_2_no_dsp_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fifo_w8_d2_S.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fifo_w8_d2_S_x.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fifo_w16_d2_S.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fifo_w16_d2_S_x.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fifo_w16_d2_S_x0.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fifo_w16_d2_S_x1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fifo_w16_d3_S.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fifo_w32_d2_S.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fifo_w32_d2_S_x.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fifo_w32_d3_S.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fifo_w32_d4_S.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fifo_w32_d4_S_x.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fifo_w32_d6_S.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_flow_control_loop_pipe.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_flow_control_loop_pipe_sequential_init.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fmul_32ns_32ns_32_4_max_dsp_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_fpext_32ns_64_2_no_dsp_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_frp_fifoout.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_frp_pipeline_valid.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_InitUndistortRectifyMapInverse_9_5_7_600_800_1_2_2_7.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_InitUndistortRectifyMapInverse_9_5_7_600_800_1_2_2_s.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_Loop_VITIS_LOOP_61_1_proc.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_Loop_VITIS_LOOP_61_1_proc_cameraMA_l_ROM_AUTO_1R.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_Loop_VITIS_LOOP_61_1_proc_cameraMA_r_ROM_AUTO_1R.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_Loop_VITIS_LOOP_61_1_proc_irA_l_ROM_AUTO_1R.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_Loop_VITIS_LOOP_70_2_proc.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_Loop_VITIS_LOOP_70_2_proc_distC_l_ROM_AUTO_1R.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_Loop_VITIS_LOOP_70_2_proc_distC_r_ROM_AUTO_1R.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mac_muladd_10ns_8ns_18ns_18_4_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_5ns_5ns_10_1_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_6ns_5ns_11_1_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_6ns_10ns_15_1_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_8s_10ns_15_1_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_11ns_8ns_18_1_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_16ns_16ns_32_1_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_16s_16s_32_1_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_17ns_20ns_37_1_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_32s_11ns_32_2_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_32s_29s_32_2_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_32s_32s_32_2_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_32s_32s_52_2_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_32s_34ns_65_2_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_33s_32s_52_2_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_34s_32s_52_2_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mul_34s_32s_65_2_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mux_3_2_8_1_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_mux_16_4_29_1_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_regslice_both.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_remap_128_1_0_7_0_600_800_1_false_2_2_2_2_2.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_remap_128_1_0_7_0_600_800_1_false_2_2_2_2_2_Block_entry1_proc.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_remap_128_1_0_7_0_600_800_1_false_2_2_2_2_Block_entry1_proc.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_remap_128_1_0_7_0_600_800_1_false_2_2_2_2_s.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_sdiv_24ns_16s_10_28_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_sitofp_32s_32_6_no_dsp_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_Sobel_0_3_0_3_600_800_1_false_2_2_2_3.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_Sobel_0_3_0_3_600_800_1_false_2_2_2_s.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_start_for_ConvertShiftAbs_U0.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_start_for_remap_128_1_0_7_0_600_800_1_false_2_2_2_2_2_U0.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_start_for_remap_128_1_0_7_0_600_800_1_false_2_2_2_2_U0.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_start_for_xFFindStereoCorrespondenceLBMNO_Loop_VITIS_LOOP_816_1_proc9_U0.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_start_for_xFImageClip_600_800_1_2_4_0_3_0_800_4_U0.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_start_for_xFImageClip_600_800_1_2_4_0_3_0_800_U0.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_start_for_xFReadOutStream_600_800_1_2_4_0_3_800_5_U0.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_start_for_xFReadOutStream_600_800_1_2_4_0_3_800_U0.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_start_for_xFSADBlockMatching_U0.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_StereoBM_15_128_16_0_2_600_800_1_false_2_2_2_s.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFFindStereoCorrespondenceLBMNO.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFFindStereoCorrespondenceLBMNO_Loop_VITIS_LOOP_816_1_proc9.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFFindStereoCorrespondenceLBMNO_Loop_VITIS_LOOP_816_1_proc9_Pipeline_VITIS_LOOP_s.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFGradientX3x3_0_4_s.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFGradientY3x3_0_4_s.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFImageClip_600_800_1_2_4_0_3_0_800_4.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFImageClip_600_800_1_2_4_0_3_0_800_4_Pipeline_loop_col_clip.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFImageClip_600_800_1_2_4_0_3_0_800_Pipeline_loop_col_clip.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFImageClip_600_800_1_2_4_0_3_0_800_s.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFImageClipUtility_1_s.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFInitUndistortRectifyMapInverseKernel.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFInitUndistortRectifyMapInverseKernel_Pipeline_loop_height_loop_width.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFInitUndistortRectifyMapInverseKernel_Pipeline_VITIS_LOOP_171_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFInitUndistortRectifyMapInverseKernel_Pipeline_VITIS_LOOP_178_2.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xfMat2AXIvideo_8_0_600_800_1_2_Pipeline_loop_col_mat2axi.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xfMat2AXIvideo_8_0_600_800_1_2_s.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFReadOutStream_600_800_1_2_4_0_3_800_5.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFReadOutStream_600_800_1_2_4_0_3_800_5_Pipeline_loop_col_clip.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFReadOutStream_600_800_1_2_4_0_3_800_Pipeline_loop_col_clip.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFReadOutStream_600_800_1_2_4_0_3_800_s.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_6.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_6_Pipeline_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_6_Pipeline_2.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_6_Pipeline_loop_width.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_6_Pipeline_loop_width_buf_RAM_Abkb.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_6_r1_RAM_AUTO_1R1W.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_1.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_2.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_Pipeline_loop_width.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_s.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFRemapLI_0_0_1_7_128_600_800_1_2_2_2_2_false_s_r1_RAM_AUTO_1R1W.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFSADBlockMatching.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFSADBlockMatching_Pipeline_loop_row_loop_mux_loop_col.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFSADBlockMatching_Pipeline_loop_row_loop_mux_loop_col_edge_neighbor_RAM_AUTOQgW.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFSADBlockMatching_Pipeline_loop_row_loop_mux_loop_col_left_line_buf_RAM_AUTOmb6.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFSADBlockMatching_Pipeline_loop_row_loop_mux_loop_col_mind_RAM_AUTO_1R1W.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFSADBlockMatching_Pipeline_loop_row_loop_mux_loop_col_minsad_RAM_AUTO_1R1W.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFSADBlockMatching_Pipeline_loop_row_loop_mux_loop_col_right_line_buf_14_RAM_PgM.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFSADBlockMatching_Pipeline_loop_row_loop_mux_loop_col_right_line_buf_RAM_1WNBew.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFSADBlockMatching_Pipeline_loop_row_loop_mux_loop_col_skip_RAM_AUTO_1R1W.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFSobel3x3_1_1_0_4_s.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFSobelFilter3x3_0_3_600_800_1_0_4_1_2_2_2_1_6_800_false_s.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFSobelFilter3x3_0_3_600_800_1_0_4_1_2_2_2_1_6_800_false_s_buf_RAM_S2P_BRAM_1jbC.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFSobelFilter3x3_Pipeline_Clear_Row_Loop.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm_xFSobelFilter3x3_Pipeline_Col_Loop.vhd" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/vhdl/stereolbm_axis_cambm.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/ip/stereolbm_axis_cambm_fcmp_32ns_32ns_1_2_no_dsp_1_ip.v" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/ip/stereolbm_axis_cambm_fmul_32ns_32ns_32_4_max_dsp_1_ip.v" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/ip/stereolbm_axis_cambm_fpext_32ns_64_2_no_dsp_1_ip.v" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/132c/hdl/ip/stereolbm_axis_cambm_sitofp_32s_32_6_no_dsp_1_ip.v" \
  "../../../bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/sim/design_1_stereolbm_axis_cambm_0_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_protocol_converter_v2_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8c02/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_clock_converter_v2_1_27 $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/29db/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"$ref_dir/../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/aed8/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"../../../../ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_stereolbm_axis_cambm_0_1/drivers/stereolbm_axis_cambm_v1_0/src" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_auto_cc_0/sim/design_1_auto_cc_0.v" \
  "../../../bd/design_1/ip/design_1_auto_cc_1/sim/design_1_auto_cc_1.v" \
  "../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
  "../../../bd/design_1/ip/design_1_auto_pc_2/sim/design_1_auto_pc_2.v" \
  "../../../bd/design_1/ip/design_1_auto_pc_3/sim/design_1_auto_pc_3.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/sim/design_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.design_1 xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.design_1 -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file


  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log design_1_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-step]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-reset_log]\n\
Usage: design_1.sh [-keep_index]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
