# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Santiago/OneDrive/Escritorio/ov5640_sv_ed_800x600_v1/ov5640_sv_ed.srcs/sources_1/bd/design_1/ip/design_1_axis_subset_converter_3_2/design_1_axis_subset_converter_3_2.xci
# IP: The module: 'design_1_axis_subset_converter_3_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Santiago/OneDrive/Escritorio/ov5640_sv_ed_800x600_v1/ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_3_2/design_1_axis_subset_converter_3_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_subset_converter_3_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Santiago/OneDrive/Escritorio/ov5640_sv_ed_800x600_v1/ov5640_sv_ed.srcs/sources_1/bd/design_1/ip/design_1_axis_subset_converter_3_2/design_1_axis_subset_converter_3_2.xci
# IP: The module: 'design_1_axis_subset_converter_3_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Santiago/OneDrive/Escritorio/ov5640_sv_ed_800x600_v1/ov5640_sv_ed.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_3_2/design_1_axis_subset_converter_3_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_subset_converter_3_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
