// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module stereolbm_axis_cambm_xfExtractPixels_1_1_0_s (
        ap_ready,
        val1_val,
        ap_return
);


output   ap_ready;
input  [7:0] val1_val;
output  [7:0] ap_return;

assign ap_ready = 1'b1;

assign ap_return = val1_val;

endmodule //stereolbm_axis_cambm_xfExtractPixels_1_1_0_s
