-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    vid_inL_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    vid_inL_TVALID : IN STD_LOGIC;
    vid_inL_TREADY : OUT STD_LOGIC;
    vid_inL_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    vid_inL_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    vid_inL_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    vid_inL_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    vid_inL_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    vid_inL_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
    imgL_in_data_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    imgL_in_data_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    imgL_in_data_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    imgL_in_data_full_n : IN STD_LOGIC;
    imgL_in_data_write : OUT STD_LOGIC;
    imgL_in_rows_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    imgL_in_rows_c_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    imgL_in_rows_c_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    imgL_in_rows_c_full_n : IN STD_LOGIC;
    imgL_in_rows_c_write : OUT STD_LOGIC;
    imgL_in_cols_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    imgL_in_cols_c_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    imgL_in_cols_c_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    imgL_in_cols_c_full_n : IN STD_LOGIC;
    imgL_in_cols_c_write : OUT STD_LOGIC );
end;


architecture behav of stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal imgL_in_rows_c_blk_n : STD_LOGIC;
    signal imgL_in_cols_c_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal empty_fu_258_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_reg_351 : STD_LOGIC_VECTOR (9 downto 0);
    signal cmp91_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp91_reg_380 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_17_fu_297_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal i_17_reg_393 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_start : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_done : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_vid_inL_TREADY : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_axi_last_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_axi_last_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_axi_data_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_axi_data_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_start : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_done : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_imgL_in_data_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_imgL_in_data_write : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_vid_inL_TREADY : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_last_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_last_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_axi_data_5_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_axi_data_5_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_start : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_done : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_vid_inL_TREADY : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_axi_last_4_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_axi_last_4_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_axi_data_4_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_axi_data_4_out_ap_vld : STD_LOGIC;
    signal axi_last_2_reg_142 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal axi_last_2_lcssa_reg_152 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal icmp_ln129_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_data_2_lcssa_reg_163 : STD_LOGIC_VECTOR (7 downto 0);
    signal last_0_lcssa_reg_173 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal axi_data_2_fu_90 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal axi_last_4_loc_fu_98 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_86 : STD_LOGIC_VECTOR (9 downto 0);
    signal start_2_fu_94 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln129_fu_288_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal regslice_both_vid_inL_V_data_V_U_apdone_blk : STD_LOGIC;
    signal vid_inL_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal vid_inL_TVALID_int_regslice : STD_LOGIC;
    signal vid_inL_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_vid_inL_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vid_inL_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal vid_inL_TKEEP_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_vid_inL_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vid_inL_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vid_inL_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal vid_inL_TSTRB_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_vid_inL_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vid_inL_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vid_inL_V_user_V_U_apdone_blk : STD_LOGIC;
    signal vid_inL_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_vid_inL_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vid_inL_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vid_inL_V_last_V_U_apdone_blk : STD_LOGIC;
    signal vid_inL_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_vid_inL_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vid_inL_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vid_inL_V_id_V_U_apdone_blk : STD_LOGIC;
    signal vid_inL_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_vid_inL_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vid_inL_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vid_inL_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal vid_inL_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_vid_inL_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vid_inL_V_dest_V_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        vid_inL_TVALID : IN STD_LOGIC;
        vid_inL_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        vid_inL_TREADY : OUT STD_LOGIC;
        vid_inL_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_last_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        axi_last_out_ap_vld : OUT STD_LOGIC;
        axi_data_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        axi_data_out_ap_vld : OUT STD_LOGIC );
    end component;


    component stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        vid_inL_TVALID : IN STD_LOGIC;
        imgL_in_data_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        imgL_in_data_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        imgL_in_data_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        imgL_in_data_full_n : IN STD_LOGIC;
        imgL_in_data_write : OUT STD_LOGIC;
        start_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_data_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        axi_last_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (9 downto 0);
        vid_inL_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        vid_inL_TREADY : OUT STD_LOGIC;
        vid_inL_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        last_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        last_out_ap_vld : OUT STD_LOGIC;
        axi_data_5_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        axi_data_5_out_ap_vld : OUT STD_LOGIC );
    end component;


    component stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        vid_inL_TVALID : IN STD_LOGIC;
        axi_last_2_lcssa : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_data_2_lcssa : IN STD_LOGIC_VECTOR (7 downto 0);
        last_0_lcssa : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        vid_inL_TREADY : OUT STD_LOGIC;
        vid_inL_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        vid_inL_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_last_4_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        axi_last_4_out_ap_vld : OUT STD_LOGIC;
        axi_data_4_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        axi_data_4_out_ap_vld : OUT STD_LOGIC );
    end component;


    component stereolbm_axis_cambm_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185 : component stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_start,
        ap_done => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_done,
        ap_idle => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_idle,
        ap_ready => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_ready,
        vid_inL_TVALID => vid_inL_TVALID_int_regslice,
        vid_inL_TDATA => vid_inL_TDATA_int_regslice,
        vid_inL_TREADY => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_vid_inL_TREADY,
        vid_inL_TKEEP => vid_inL_TKEEP_int_regslice,
        vid_inL_TSTRB => vid_inL_TSTRB_int_regslice,
        vid_inL_TUSER => vid_inL_TUSER_int_regslice,
        vid_inL_TLAST => vid_inL_TLAST_int_regslice,
        vid_inL_TID => vid_inL_TID_int_regslice,
        vid_inL_TDEST => vid_inL_TDEST_int_regslice,
        axi_last_out => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_axi_last_out,
        axi_last_out_ap_vld => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_axi_last_out_ap_vld,
        axi_data_out => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_axi_data_out,
        axi_data_out_ap_vld => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_axi_data_out_ap_vld);

    grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205 : component stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_start,
        ap_done => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_done,
        ap_idle => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_idle,
        ap_ready => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_ready,
        vid_inL_TVALID => vid_inL_TVALID_int_regslice,
        imgL_in_data_din => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_imgL_in_data_din,
        imgL_in_data_num_data_valid => ap_const_lv2_0,
        imgL_in_data_fifo_cap => ap_const_lv2_0,
        imgL_in_data_full_n => imgL_in_data_full_n,
        imgL_in_data_write => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_imgL_in_data_write,
        start_2 => start_2_fu_94,
        axi_data_2 => axi_data_2_fu_90,
        axi_last_2 => axi_last_2_reg_142,
        p_read1 => empty_reg_351,
        vid_inL_TDATA => vid_inL_TDATA_int_regslice,
        vid_inL_TREADY => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_vid_inL_TREADY,
        vid_inL_TKEEP => vid_inL_TKEEP_int_regslice,
        vid_inL_TSTRB => vid_inL_TSTRB_int_regslice,
        vid_inL_TUSER => vid_inL_TUSER_int_regslice,
        vid_inL_TLAST => vid_inL_TLAST_int_regslice,
        vid_inL_TID => vid_inL_TID_int_regslice,
        vid_inL_TDEST => vid_inL_TDEST_int_regslice,
        last_out => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_last_out,
        last_out_ap_vld => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_last_out_ap_vld,
        axi_data_5_out => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_axi_data_5_out,
        axi_data_5_out_ap_vld => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_axi_data_5_out_ap_vld);

    grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232 : component stereolbm_axis_cambm_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_start,
        ap_done => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_done,
        ap_idle => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_idle,
        ap_ready => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_ready,
        vid_inL_TVALID => vid_inL_TVALID_int_regslice,
        axi_last_2_lcssa => axi_last_2_lcssa_reg_152,
        axi_data_2_lcssa => axi_data_2_lcssa_reg_163,
        last_0_lcssa => last_0_lcssa_reg_173,
        vid_inL_TDATA => vid_inL_TDATA_int_regslice,
        vid_inL_TREADY => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_vid_inL_TREADY,
        vid_inL_TKEEP => vid_inL_TKEEP_int_regslice,
        vid_inL_TSTRB => vid_inL_TSTRB_int_regslice,
        vid_inL_TUSER => vid_inL_TUSER_int_regslice,
        vid_inL_TLAST => vid_inL_TLAST_int_regslice,
        vid_inL_TID => vid_inL_TID_int_regslice,
        vid_inL_TDEST => vid_inL_TDEST_int_regslice,
        axi_last_4_out => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_axi_last_4_out,
        axi_last_4_out_ap_vld => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_axi_last_4_out_ap_vld,
        axi_data_4_out => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_axi_data_4_out,
        axi_data_4_out_ap_vld => grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_axi_data_4_out_ap_vld);

    regslice_both_vid_inL_V_data_V_U : component stereolbm_axis_cambm_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => vid_inL_TDATA,
        vld_in => vid_inL_TVALID,
        ack_in => regslice_both_vid_inL_V_data_V_U_ack_in,
        data_out => vid_inL_TDATA_int_regslice,
        vld_out => vid_inL_TVALID_int_regslice,
        ack_out => vid_inL_TREADY_int_regslice,
        apdone_blk => regslice_both_vid_inL_V_data_V_U_apdone_blk);

    regslice_both_vid_inL_V_keep_V_U : component stereolbm_axis_cambm_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => vid_inL_TKEEP,
        vld_in => vid_inL_TVALID,
        ack_in => regslice_both_vid_inL_V_keep_V_U_ack_in,
        data_out => vid_inL_TKEEP_int_regslice,
        vld_out => regslice_both_vid_inL_V_keep_V_U_vld_out,
        ack_out => vid_inL_TREADY_int_regslice,
        apdone_blk => regslice_both_vid_inL_V_keep_V_U_apdone_blk);

    regslice_both_vid_inL_V_strb_V_U : component stereolbm_axis_cambm_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => vid_inL_TSTRB,
        vld_in => vid_inL_TVALID,
        ack_in => regslice_both_vid_inL_V_strb_V_U_ack_in,
        data_out => vid_inL_TSTRB_int_regslice,
        vld_out => regslice_both_vid_inL_V_strb_V_U_vld_out,
        ack_out => vid_inL_TREADY_int_regslice,
        apdone_blk => regslice_both_vid_inL_V_strb_V_U_apdone_blk);

    regslice_both_vid_inL_V_user_V_U : component stereolbm_axis_cambm_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => vid_inL_TUSER,
        vld_in => vid_inL_TVALID,
        ack_in => regslice_both_vid_inL_V_user_V_U_ack_in,
        data_out => vid_inL_TUSER_int_regslice,
        vld_out => regslice_both_vid_inL_V_user_V_U_vld_out,
        ack_out => vid_inL_TREADY_int_regslice,
        apdone_blk => regslice_both_vid_inL_V_user_V_U_apdone_blk);

    regslice_both_vid_inL_V_last_V_U : component stereolbm_axis_cambm_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => vid_inL_TLAST,
        vld_in => vid_inL_TVALID,
        ack_in => regslice_both_vid_inL_V_last_V_U_ack_in,
        data_out => vid_inL_TLAST_int_regslice,
        vld_out => regslice_both_vid_inL_V_last_V_U_vld_out,
        ack_out => vid_inL_TREADY_int_regslice,
        apdone_blk => regslice_both_vid_inL_V_last_V_U_apdone_blk);

    regslice_both_vid_inL_V_id_V_U : component stereolbm_axis_cambm_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => vid_inL_TID,
        vld_in => vid_inL_TVALID,
        ack_in => regslice_both_vid_inL_V_id_V_U_ack_in,
        data_out => vid_inL_TID_int_regslice,
        vld_out => regslice_both_vid_inL_V_id_V_U_vld_out,
        ack_out => vid_inL_TREADY_int_regslice,
        apdone_blk => regslice_both_vid_inL_V_id_V_U_apdone_blk);

    regslice_both_vid_inL_V_dest_V_U : component stereolbm_axis_cambm_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => vid_inL_TDEST,
        vld_in => vid_inL_TVALID,
        ack_in => regslice_both_vid_inL_V_dest_V_U_ack_in,
        data_out => vid_inL_TDEST_int_regslice,
        vld_out => regslice_both_vid_inL_V_dest_V_U_vld_out,
        ack_out => vid_inL_TREADY_int_regslice,
        apdone_blk => regslice_both_vid_inL_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln129_fu_292_p2 = ap_const_lv1_0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_start_reg <= ap_const_logic_0;
            else
                if (((cmp91_reg_380 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln129_fu_292_p2 = ap_const_lv1_1))) then 
                    grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    axi_data_2_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_axi_data_4_out_ap_vld = ap_const_logic_1))) then 
                axi_data_2_fu_90 <= grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_axi_data_4_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_axi_data_out_ap_vld = ap_const_logic_1))) then 
                axi_data_2_fu_90 <= grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_axi_data_out;
            end if; 
        end if;
    end process;

    axi_data_2_lcssa_reg_163_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((cmp91_reg_380 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln129_fu_292_p2 = ap_const_lv1_1))) then 
                axi_data_2_lcssa_reg_163 <= axi_data_2_fu_90;
            elsif (((cmp91_reg_380 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                axi_data_2_lcssa_reg_163 <= grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_axi_data_5_out;
            end if; 
        end if;
    end process;

    axi_last_2_lcssa_reg_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((cmp91_reg_380 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln129_fu_292_p2 = ap_const_lv1_1))) then 
                axi_last_2_lcssa_reg_152 <= axi_last_2_reg_142;
            elsif (((cmp91_reg_380 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                axi_last_2_lcssa_reg_152 <= grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_last_out;
            end if; 
        end if;
    end process;

    axi_last_2_reg_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                axi_last_2_reg_142 <= axi_last_4_loc_fu_98;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                axi_last_2_reg_142 <= grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_axi_last_out;
            end if; 
        end if;
    end process;

    i_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((imgL_in_cols_c_full_n = ap_const_logic_0) or (imgL_in_rows_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_86 <= ap_const_lv10_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                i_fu_86 <= i_17_reg_393;
            end if; 
        end if;
    end process;

    last_0_lcssa_reg_173_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((cmp91_reg_380 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln129_fu_292_p2 = ap_const_lv1_1))) then 
                last_0_lcssa_reg_173 <= ap_const_lv1_0;
            elsif (((cmp91_reg_380 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                last_0_lcssa_reg_173 <= grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_last_out;
            end if; 
        end if;
    end process;

    start_2_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((imgL_in_cols_c_full_n = ap_const_logic_0) or (imgL_in_rows_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                start_2_fu_94 <= ap_const_lv1_1;
            elsif (((cmp91_reg_380 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                start_2_fu_94 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_axi_last_4_out_ap_vld = ap_const_logic_1))) then
                axi_last_4_loc_fu_98 <= grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_axi_last_4_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((imgL_in_cols_c_full_n = ap_const_logic_0) or (imgL_in_rows_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                cmp91_reg_380 <= cmp91_fu_262_p2;
                empty_reg_351 <= empty_fu_258_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                i_17_reg_393 <= i_17_fu_297_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, imgL_in_rows_c_full_n, imgL_in_cols_c_full_n, cmp91_reg_380, ap_CS_fsm_state5, grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_done, grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_done, grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_done, icmp_ln129_fu_292_p2, ap_CS_fsm_state3, ap_CS_fsm_state6, ap_CS_fsm_state9)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((imgL_in_cols_c_full_n = ap_const_logic_0) or (imgL_in_rows_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln129_fu_292_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((cmp91_reg_380 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln129_fu_292_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg, imgL_in_rows_c_full_n, imgL_in_cols_c_full_n)
    begin
        if (((imgL_in_cols_c_full_n = ap_const_logic_0) or (imgL_in_rows_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_done)
    begin
        if ((grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_done)
    begin
        if ((grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_done)
    begin
        if ((grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, imgL_in_rows_c_full_n, imgL_in_cols_c_full_n)
    begin
                ap_block_state1 <= ((imgL_in_cols_c_full_n = ap_const_logic_0) or (imgL_in_rows_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5, icmp_ln129_fu_292_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln129_fu_292_p2 = ap_const_lv1_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    cmp91_fu_262_p2 <= "1" when (signed(p_read1) > signed(ap_const_lv32_0)) else "0";
    empty_fu_258_p1 <= p_read1(10 - 1 downto 0);
    grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_start <= grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_ap_start_reg;
    grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_start <= grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_ap_start_reg;
    grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_start <= grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_ap_start_reg;
    i_17_fu_297_p2 <= std_logic_vector(unsigned(i_fu_86) + unsigned(ap_const_lv10_1));
    icmp_ln129_fu_292_p2 <= "1" when (signed(zext_ln129_fu_288_p1) < signed(p_read)) else "0";

    imgL_in_cols_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgL_in_cols_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgL_in_cols_c_blk_n <= imgL_in_cols_c_full_n;
        else 
            imgL_in_cols_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    imgL_in_cols_c_din <= p_read1;

    imgL_in_cols_c_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgL_in_rows_c_full_n, imgL_in_cols_c_full_n)
    begin
        if ((not(((imgL_in_cols_c_full_n = ap_const_logic_0) or (imgL_in_rows_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgL_in_cols_c_write <= ap_const_logic_1;
        else 
            imgL_in_cols_c_write <= ap_const_logic_0;
        end if; 
    end process;

    imgL_in_data_din <= grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_imgL_in_data_din;

    imgL_in_data_write_assign_proc : process(grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_imgL_in_data_write, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            imgL_in_data_write <= grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_imgL_in_data_write;
        else 
            imgL_in_data_write <= ap_const_logic_0;
        end if; 
    end process;


    imgL_in_rows_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgL_in_rows_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgL_in_rows_c_blk_n <= imgL_in_rows_c_full_n;
        else 
            imgL_in_rows_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    imgL_in_rows_c_din <= p_read;

    imgL_in_rows_c_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgL_in_rows_c_full_n, imgL_in_cols_c_full_n)
    begin
        if ((not(((imgL_in_cols_c_full_n = ap_const_logic_0) or (imgL_in_rows_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgL_in_rows_c_write <= ap_const_logic_1;
        else 
            imgL_in_rows_c_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state5, icmp_ln129_fu_292_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln129_fu_292_p2 = ap_const_lv1_0))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    vid_inL_TREADY <= regslice_both_vid_inL_V_data_V_U_ack_in;

    vid_inL_TREADY_int_regslice_assign_proc : process(grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_vid_inL_TREADY, grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_vid_inL_TREADY, grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_vid_inL_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state6, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            vid_inL_TREADY_int_regslice <= grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_last_hunt_fu_232_vid_inL_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            vid_inL_TREADY_int_regslice <= grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_col_zxi2mat_fu_205_vid_inL_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            vid_inL_TREADY_int_regslice <= grp_AXIvideo2xfMat_8_0_600_800_1_2_1_Pipeline_loop_start_hunt_fu_185_vid_inL_TREADY;
        else 
            vid_inL_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln129_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_86),32));
end behav;
